name: Discord Leveling
on:
  push:
    branches: [main]

jobs:
  run_command:
    runs-on: ubuntu-latest
    steps:
      - name: Send message via bot
        env:
          BOT_TOKEN: ${{ secrets.DISCHORD_BOT_TOKEN }}
          CHANNEL_ID: '1417079982848479343'
        run: |
          curl -s -X POST "https://discord.com/api/v10/channels/$CHANNEL_ID/messages" \
            -H "Authorization: Bot $BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d @- <<'JSON'
          {
            "content": "/echo message:Test3"
          }
          JSON
