name: Discord Leveling
on:
  push:
    branches: [main]

jobs:
  run_command:
    runs-on: ubuntu-latest
    steps:
      - name: Send message via bot
        env:
          BOT_TOKEN: ${{ secrets.DISHCORD_BOT_TOKEN }}
          CHANNEL_ID: '123456789012345678'
        run: |
          curl -X POST "https://discord.com/api/v10/channels/$CHANNEL_ID/messages" \
            -H "Authorization: Bot $BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"content":"/echo message:Test2 channel:#level"}' \
            "https://discord.com/api/v10/channels/1417079982848479343/messages"
