name: Discord Leveling
on:
  push:
    branches: [main]

jobs:
  run_command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get stats
        run: |
          author_name=$(git log -1 --pretty=format:'%ae')
          added=$(git show --numstat --pretty="" HEAD | awk '{sum += $1} END {print sum+0}')
          echo "ADDITIONS=$added" >> $GITHUB_ENV
          echo "AUTHOR=$author_name" >> $GITHUB_ENV
      - name: Send message via bot
        env:
          BOT_TOKEN: ${{ secrets.DISCHORD_BOT_TOKEN }}
          CHANNEL_ID: '1417079982848479343'
        run: |
          payload=$(jq -nc --arg c "new Commit by $AUTHOR $ADDITIONS" '{content:$c}')
          curl -s -X POST "https://atlas.bot/api/guilds/1417072674219229307/actions/05652f94-93cf-4515-a2cd-73f1cabe0162/webhook/07b5213c6bac954da52a57918d9b32110b028dd647e51c8536bd5cfcefd6f6c7" \
            -H "Authorization: Bot $BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            --ssl-no-revoke
          
          
